version: "3.4"

services:
  devork:
    container_name: "devork"
    restart: unless-stopped
    build: ./
    tty: true
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./:/usr/app:rw,cached
    ports:
      - "80:80"
